version: "3.2"

services:
  code-node1:
    container_name: code-node1
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9001:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=1"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node2:
    container_name: code-node2
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9002:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=2"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node3:
    container_name: code-node3
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9003:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=3"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node4:
    container_name: code-node4
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9004:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=4"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node5:
    container_name: code-node5
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9005:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=5"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node6:
    container_name: code-node6
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9006:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=6"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node7:
    container_name: code-node7
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9007:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=7"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node8:
    container_name: code-node8
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9008:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=8"
      - "com.centurylinklabs.watchtower.enable=true"

  code-node9:
    container_name: code-node9
    image: docker.io/collabora/code
    restart: always
    ports:
      - 9009:9980
    environment:
      - dictionaries=fr_FR
    cap_add:
      - MKNOD
    volumes:
      - /collabora_conf/coolwsd.xml:/etc/coolwsd/coolwsd.xml:ro
    labels:
      - "com.centurylinklabs.watchtower.update-order=9"
      - "com.centurylinklabs.watchtower.enable=true"