version: '3.2'

services:
  storage-replica-node1:
    container_name: storage-replica-node1
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - 9090:9001
      - 9091:9000
    volumes:
      - type: bind
        source: /replica-data1
        target: /bitnami/minio/data
      - type: volume
        source: certs1
        target: /certs
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=storage-replica-node1,storage-replica-node2,storage-replica-node3,storage-replica-node4,storage-replica-node5,storage-replica-node6
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    networks:
      network:
        ipv4_address: 172.50.0.11
    labels:
      - "com.centurylinklabs.watchtower.update-order=1"
      - "com.centurylinklabs.watchtower.enable=true"

  storage-replica-node2:
    container_name: storage-replica-node2
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - 9092:9000
    volumes:
      - type: bind
        source: /replica-data2
        target: /bitnami/minio/data
      - type: volume
        source: certs2
        target: /certs
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=storage-replica-node1,storage-replica-node2,storage-replica-node3,storage-replica-node4,storage-replica-node5,storage-replica-node6
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    networks:
      network:
        ipv4_address: 172.50.0.12
    labels:
      - "com.centurylinklabs.watchtower.update-order=2"
      - "com.centurylinklabs.watchtower.enable=true"

  storage-replica-node3:
    container_name: storage-replica-node3
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - 9093:9000
    volumes:
      - type: bind
        source: /replica-data3
        target: /bitnami/minio/data
      - type: volume
        source: certs3
        target: /certs
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=storage-replica-node1,storage-replica-node2,storage-replica-node3,storage-replica-node4,storage-replica-node5,storage-replica-node6
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    networks:
      network:
        ipv4_address: 172.50.0.13
    labels:
      - "com.centurylinklabs.watchtower.update-order=3"
      - "com.centurylinklabs.watchtower.enable=true"

  storage-replica-node4:
    container_name: storage-replica-node4
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - 9094:9000
    volumes:
      - type: bind
        source: /replica-data4
        target: /bitnami/minio/data
      - type: volume
        source: certs4
        target: /certs
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=storage-replica-node1,storage-replica-node2,storage-replica-node3,storage-replica-node4,storage-replica-node5,storage-replica-node6
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    networks:
      network:
        ipv4_address: 172.50.0.14
    labels:
      - "com.centurylinklabs.watchtower.update-order=4"
      - "com.centurylinklabs.watchtower.enable=true"

  storage-replica-node5:
    container_name: storage-replica-node5
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - 9095:9000
    volumes:
      - type: bind
        source: /replica-data5
        target: /bitnami/minio/data
      - type: volume
        source: certs5
        target: /certs
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=storage-replica-node1,storage-replica-node2,storage-replica-node3,storage-replica-node4,storage-replica-node5,storage-replica-node6
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    networks:
      network:
        ipv4_address: 172.50.0.15
    labels:
      - "com.centurylinklabs.watchtower.update-order=5"
      - "com.centurylinklabs.watchtower.enable=true"

  storage-replica-node6:
    container_name: storage-replica-node6
    image: 'bitnami/minio:latest'
    user: root
    ports:
      - 9096:9000
    volumes:
      - type: bind
        source: /replica-data6
        target: /bitnami/minio/data
      - type: volume
        source: certs6
        target: /certs
    environment:
      - MINIO_ROOT_USER=
      - MINIO_ROOT_PASSWORD=pass
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=storage-replica-node1,storage-replica-node2,storage-replica-node3,storage-replica-node4,storage-replica-node5,storage-replica-node6
      - MINIO_SKIP_CLIENT=yes
      - MINIO_STORAGE_CLASS_STANDARD=EC:2
    networks:
      network:
        ipv4_address: 172.50.0.16
    labels:
      - "com.centurylinklabs.watchtower.update-order=6"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  network:
    name: minio-replica-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.50.0.0/24
          gateway: 172.50.0.1

volumes:
  certs1:
    driver: local
  certs2:
    driver: local
  certs3:
    driver: local
  certs4:
    driver: local
  certs5:
    driver: local
  certs6:
    driver: local