version: "3.2"

services:
  app-next-01:
    container_name: app-next-01
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8081:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.11
    labels:
      - "com.centurylinklabs.watchtower.update-order=1"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-02:
    container_name: app-next-02
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8082:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.12
    labels:
      - "com.centurylinklabs.watchtower.update-order=2"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-03:
    container_name: app-next-03
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.13
    labels:
      - "com.centurylinklabs.watchtower.update-order=3"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-04:
    container_name: app-next-04
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8084:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.14
    labels:
      - "com.centurylinklabs.watchtower.update-order=4"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-05:
    container_name: app-next-05
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8085:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.15
    labels:
      - "com.centurylinklabs.watchtower.update-order=5"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-06:
    container_name: app-next-06
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8086:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.16
    labels:
      - "com.centurylinklabs.watchtower.update-order=6"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-07:
    container_name: app-next-07
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8087:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.17
    labels:
      - "com.centurylinklabs.watchtower.update-order=7"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-08:
    container_name: app-next-08
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8088:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.18
    labels:
      - "com.centurylinklabs.watchtower.update-order=8"
      - "com.centurylinklabs.watchtower.enable=true"

  app-next-09:
    container_name: app-next-09
    image: docker.io/nextcloud
    restart: always
    ports:
      - 8089:80
    volumes:
      - type: bind
        source: /opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: volume
        source: nextcloud
        target: /var/www/html
      - type: volume
        source: apps
        target: /var/www/html/custom_apps
      - type: volume
        source: config
        target: /var/www/html/config
      - type: volume
        source: data
        target: /var/www/html/data
    environment:
      - PHP_UPLOAD_LIMIT=2G
      - PHP_MEMORY_LIMIT=1G
    networks:
      network:
        ipv4_address: 172.10.0.19
    labels:
      - "com.centurylinklabs.watchtower.update-order=9"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  nextcloud:
    driver: local
  apps:
    driver: local
  config:
    driver: local
  data:
    driver: local

networks:
  network:
    name: next-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1